default:
  default_args:
    owner: "default_owner"
    start_date: 2018-03-01
    retries: 5
    retry_delay_sec: 5
  schedule_interval: "@hourly"
  on_success_callback_name: print_hello
  on_success_callback_file: /usr/local/airflow/dags/dag_example1.py
  on_failure_callback_name: print_hello
  on_failure_callback_file: /usr/local/airflow/dags/dag_example1.py
