default:
  default_args:
    owner: "default_owner"
    start_date: 2022-07-06
    retries: 5
    retry_delay_sec: 5
  schedule_interval: "@hourly	"
  description: 'Dag Universidades B y G'


tasks:
  extract_b:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: extract
    python_callable_file: /home/lnicolas/acceleracion_alkemy/extract_b.py

  transform_b:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: transform
    python_callable_file: /home/lnicolas/acceleracion_alkemy/transform_b.py

  load_b:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: upload
    python_callable_file: /home/lnicolas/acceleracion_alkemy/load_b.py

  extract_g:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: Extract
    python_callable_file: /home/lnicolas/acceleracion_alkemy/sql_operator.py

  transform_g:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: Transform
    python_callable_file: /home/lnicolas/acceleracion_alkemy/pandas_norm.py

  load_g:
    operator: airflow.operators.python_operator.PythonOperator
    python_callable_name: Load
    python_callable_file: /home/lnicolas/acceleracion_alkemy/s3_operator.py