dag:
  default_args:
    owner: 'pablo_correa'
    start_date: 2022-07-05
    description: 'ETL DAG for two universities (group A)'
    schedule_interval: '0 * * * *'
    catchup: False
    retries: 5
    retry_delay_sec: 300
    dag_name: dynamic_dag_group_A
  tasks:
    scrape:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: scrape
      python_callable_file: /home/pablocorrea/airflow/dags/scripts_A/extract.py
    process:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: process
      python_callable_file: /home/pablocorrea/airflow/dags/scripts_A/process.py
      dependencies: [scrape]
    save:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: save
      python_callable_file: /home/pablocorrea/airflow/dags/scripts_A/save.py
      op_kwargs:
        bucket_name: cohorte-junio-a192d78b
      dependencies: [process]