default:
  default_args:
    owner: "Cristian Rosas"
    start_date: 2022-07-08
    end_date: 2022-08-08
    retries: 5
    retry_delay_sec: 300
  concurrency: 1
  max_active_runs: 1
  dagrun_timeout_sec: 600
  default_view: "tree"
  orientation: "LR"
  schedule_interval: "0 1 * * *"
  on_success_callback_name: extract_from_db
  on_success_callback_file: /home/cris/airflow/dags/scripts/extract_data.py
  on_success_callback_name: process_data_univ
  on_success_callback_file: /home/cris/airflow/dags/scripts/process_data.py
  on_success_callback_name: upload_to_s3
  on_success_callback_file: /home/cris/airflow/dags/scripts/upload_file.py


dag_dinamic_uni_E:
  default_args:
    owner: "Cristian Rosas"
    start_date: 2 days
  description: "Dynamic DAGs from Group E universities"
  schedule_interval: "0 3 * * *"
  tasks:
    extract:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: extract_from_db
      python_callable_file: /home/cris/airflow/dags/scripts/extract_data.py
    transform:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: process_data_univ
      python_callable_file: /home/cris/airflow/dags/scripts/process_data.py
      dependencies: [extract]
    load:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: upload_to_s3
      python_callable_file: /home/cris/airflow/dags/scripts/upload_file.py
      op_kwargs:
        bucket_name: cohorte-junio-a192d78b
      dependencies: [transform]
